/**
 * Basic Theme Presets
 * Migrated existing 10 themes to new theme system format
 */

import type { ThemePreset } from '../types';

export const defaultTheme: ThemePreset = {
  id: 'default',
  name: 'Default',
  category: 'basic',
  description: 'Clean and modern default theme with gradient background',
  colors: {
    cardBackground: 'linear-gradient(135deg, var(--card) 0%, oklch(from var(--accent) l c h / 0.1) 100%)',
    cardBorder: 'var(--border)',
    cellBackground: 'var(--card)',
    cellBorder: 'var(--border)',
    cellText: 'var(--foreground)',
    cellHoverBackground: 'oklch(from var(--card) calc(l * 0.95) c h)',
    markedBackground: 'oklch(from var(--card) calc(l * 0.9) c h)',
    markedBorder: 'var(--border)',
    markedText: 'oklch(from var(--foreground) l c h / 0.5)',
    freeBackground: 'var(--secondary)',
    freeBorder: 'var(--border)',
    freeText: 'var(--secondary-foreground)',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: { card: 12, cell: 8 },
    shadows: {
      card: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: false,
    headerType: 'none',
  },
  customizable: [
    'colors.cardBackground',
    'colors.cellBackground',
    'colors.freeBackground',
    'effects.borderRadius',
  ],
  tags: ['modern', 'clean', 'simple'],
};

export const vintageTheme: ThemePreset = {
  id: 'vintage',
  name: 'Vintage',
  category: 'basic',
  description: 'Classic bingo hall aesthetic with bold red accents',
  colors: {
    cardBackground: '#E8DCC4',
    cardBorder: '#E63946',
    cellBackground: '#E8DCC4',
    cellBorder: '#E63946',
    cellText: '#E63946',
    cellHoverBackground: '#F5F0E6',
    markedBackground: '#F5F0E6',
    markedBorder: '#E63946',
    markedText: 'rgba(230, 57, 70, 0.5)',
    freeBackground: '#E63946',
    freeBorder: '#E63946',
    freeText: '#FFFFFF',
    headerBackground: '#E8DCC4',
    headerText: '#E63946',
    headerBorder: '#E63946',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 3,
    borderRadius: { card: 0, cell: 0 },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 600,
    cellTextTransform: 'none',
    headerFontSize: 3,
    headerFontWeight: 900,
    headerLetterSpacing: -0.02,
    freeFontSize: 0.75,
    freeFontWeight: 900,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: true,
    headerType: 'vintage',
  },
  customizable: ['colors.cardBackground', 'colors.cellBorder', 'colors.freeBackground'],
  tags: ['retro', 'classic', 'red', 'bingo-hall'],
};

export const whimsicalTheme: ThemePreset = {
  id: 'whimsical',
  name: 'Whimsical',
  category: 'basic',
  description: 'Playful design with scalloped borders and pink accents',
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#B4889F',
    cellBackground: '#FFFFFF',
    cellBorder: '#B4889F',
    cellText: '#374151',
    cellHoverBackground: '#FDF2F8',
    markedBackground: '#FDF2F8',
    markedBorder: '#B4889F',
    markedText: 'rgba(55, 65, 81, 0.5)',
    freeBackground: '#F9A8D4',
    freeBorder: '#B4889F',
    freeText: '#FFFFFF',
    headerBackground: 'transparent',
    headerText: '#F9A8D4',
  },
  effects: {
    borderStyle: 'scalloped',
    borderWidth: 3,
    borderRadius: { card: 24, cell: 0 },
    shadows: {
      card: '0 0 0 1px #B4889F, inset 0 0 0 1px #B4889F',
    },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    headerFontSize: 3,
    headerFontWeight: 900,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: true,
    headerType: 'whimsical',
    showBorderDecorations: true,
  },
  customizable: ['colors.cardBorder', 'colors.freeBackground', 'colors.headerText'],
  tags: ['playful', 'fun', 'pink', 'scalloped'],
};

export const modernTheme: ThemePreset = {
  id: 'modern',
  name: 'Modern',
  category: 'basic',
  description: 'Minimalist design with BINGO letter headers',
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#E5E7EB',
    cellBackground: '#FFFFFF',
    cellBorder: '#E5E7EB',
    cellText: '#111827',
    cellHoverBackground: '#F9FAFB',
    markedBackground: '#F9FAFB',
    markedBorder: '#E5E7EB',
    markedText: 'rgba(17, 24, 39, 0.5)',
    freeBackground: '#FF6B6B',
    freeBorder: '#FF6B6B',
    freeText: '#FFFFFF',
    headerBackground: 'transparent',
    headerText: '#111827',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: { card: 12, cell: 4 },
  },
  typography: {
    fontFamily: 'serif',
    cellFontSize: 0.5625,
    cellFontWeight: 400,
    headerFontSize: 2,
    headerFontWeight: 400,
    headerLetterSpacing: 0.1,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: true,
    headerType: 'modern',
  },
  customizable: ['colors.cellBorder', 'colors.freeBackground', 'typography.fontFamily'],
  tags: ['minimal', 'clean', 'serif'],
};

export const illustratedTheme: ThemePreset = {
  id: 'illustrated',
  name: 'Illustrated',
  category: 'basic',
  description: 'Hand-drawn style with numbered cells and decorative borders',
  colors: {
    cardBackground: '#FFFFFF',
    cardBorder: '#8B7355',
    cellBackground: '#FFFFFF',
    cellBorder: '#D1D5DB',
    cellText: '#374151',
    cellHoverBackground: '#F9FAFB',
    markedBackground: '#F9FAFB',
    markedBorder: '#D1D5DB',
    markedText: 'rgba(55, 65, 81, 0.5)',
    freeBackground: '#FFFFFF',
    freeBorder: '#D1D5DB',
    freeText: '#374151',
    headerBackground: 'transparent',
    headerText: '#111827',
  },
  effects: {
    borderStyle: 'scalloped',
    borderWidth: 3,
    borderRadius: { card: 24, cell: 0 },
    shadows: {
      card: '0 0 0 1px #8B7355, inset 0 0 0 1px #8B7355',
    },
  },
  typography: {
    fontFamily: 'serif',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    headerFontSize: 2.5,
    headerFontWeight: 700,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: true,
    headerType: 'illustrated',
    showBorderDecorations: true,
  },
  customizable: ['colors.cardBorder', 'colors.cellBorder', 'typography.fontFamily'],
  tags: ['hand-drawn', 'decorative', 'numbered'],
};

export const sunsetTheme: ThemePreset = {
  id: 'sunset',
  name: 'Sunset',
  category: 'gradient',
  description: 'Warm gradient theme inspired by sunset colors',
  colors: {
    cardBackground: 'linear-gradient(135deg, #FFF7ED 0%, #FEE2E2 100%)',
    cardBorder: '#FDBA74',
    cellBackground: '#FFFFFF',
    cellBorder: '#FDBA74',
    cellText: '#7C2D12',
    cellHoverBackground: '#FFF7ED',
    markedBackground: '#FFF7ED',
    markedBorder: '#FDBA74',
    markedText: 'rgba(124, 45, 18, 0.5)',
    freeBackground: 'linear-gradient(90deg, #F97316 0%, #EC4899 100%)',
    freeBorder: '#FDBA74',
    freeText: '#FFFFFF',
    gradientStart: '#FFF7ED',
    gradientEnd: '#FEE2E2',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: { card: 12, cell: 8 },
    shadows: {
      card: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: false,
  },
  customizable: [
    'colors.gradientStart',
    'colors.gradientEnd',
    'colors.cellBorder',
    'colors.freeBackground',
  ],
  tags: ['gradient', 'warm', 'orange', 'pink'],
};

export const oceanTheme: ThemePreset = {
  id: 'ocean',
  name: 'Ocean',
  category: 'gradient',
  description: 'Cool gradient theme with ocean blues and cyans',
  colors: {
    cardBackground: 'linear-gradient(135deg, #EFF6FF 0%, #ECFEFF 100%)',
    cardBorder: '#93C5FD',
    cellBackground: '#FFFFFF',
    cellBorder: '#93C5FD',
    cellText: '#1E3A8A',
    cellHoverBackground: '#EFF6FF',
    markedBackground: '#EFF6FF',
    markedBorder: '#93C5FD',
    markedText: 'rgba(30, 58, 138, 0.5)',
    freeBackground: 'linear-gradient(90deg, #2563EB 0%, #06B6D4 100%)',
    freeBorder: '#93C5FD',
    freeText: '#FFFFFF',
    gradientStart: '#EFF6FF',
    gradientEnd: '#ECFEFF',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: { card: 12, cell: 8 },
    shadows: {
      card: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: false,
  },
  customizable: [
    'colors.gradientStart',
    'colors.gradientEnd',
    'colors.cellBorder',
    'colors.freeBackground',
  ],
  tags: ['gradient', 'cool', 'blue', 'cyan'],
};

export const forestTheme: ThemePreset = {
  id: 'forest',
  name: 'Forest',
  category: 'gradient',
  description: 'Natural gradient theme with forest greens',
  colors: {
    cardBackground: 'linear-gradient(135deg, #F0FDF4 0%, #ECFDF5 100%)',
    cardBorder: '#86EFAC',
    cellBackground: '#FFFFFF',
    cellBorder: '#86EFAC',
    cellText: '#14532D',
    cellHoverBackground: '#F0FDF4',
    markedBackground: '#F0FDF4',
    markedBorder: '#86EFAC',
    markedText: 'rgba(20, 83, 45, 0.5)',
    freeBackground: 'linear-gradient(90deg, #16A34A 0%, #10B981 100%)',
    freeBorder: '#86EFAC',
    freeText: '#FFFFFF',
    gradientStart: '#F0FDF4',
    gradientEnd: '#ECFDF5',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: { card: 12, cell: 8 },
    shadows: {
      card: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: false,
  },
  customizable: [
    'colors.gradientStart',
    'colors.gradientEnd',
    'colors.cellBorder',
    'colors.freeBackground',
  ],
  tags: ['gradient', 'nature', 'green', 'emerald'],
};

export const midnightTheme: ThemePreset = {
  id: 'midnight',
  name: 'Midnight',
  category: 'gradient',
  description: 'Dark gradient theme with purple and blue accents',
  colors: {
    cardBackground: 'linear-gradient(135deg, #1E293B 0%, #0F172A 100%)',
    cardBorder: '#64748B',
    cellBackground: '#334155',
    cellBorder: '#64748B',
    cellText: '#FFFFFF',
    cellHoverBackground: '#475569',
    markedBackground: '#475569',
    markedBorder: '#64748B',
    markedText: 'rgba(255, 255, 255, 0.5)',
    freeBackground: 'linear-gradient(90deg, #9333EA 0%, #3B82F6 100%)',
    freeBorder: '#64748B',
    freeText: '#FFFFFF',
    gradientStart: '#1E293B',
    gradientEnd: '#0F172A',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: { card: 12, cell: 8 },
    shadows: {
      card: '0 10px 15px -3px rgb(0 0 0 / 0.3), 0 4px 6px -4px rgb(0 0 0 / 0.3)',
    },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: false,
  },
  customizable: [
    'colors.gradientStart',
    'colors.gradientEnd',
    'colors.cellBackground',
    'colors.freeBackground',
  ],
  tags: ['gradient', 'dark', 'purple', 'blue'],
};

export const pastelTheme: ThemePreset = {
  id: 'pastel',
  name: 'Pastel',
  category: 'gradient',
  description: 'Soft multi-color gradient with pastel tones',
  colors: {
    cardBackground: 'linear-gradient(135deg, #FAF5FF 0%, #FCE7F3 50%, #FEF9C3 100%)',
    cardBorder: '#D8B4FE',
    cellBackground: '#FFFFFF',
    cellBorder: '#D8B4FE',
    cellText: '#581C87',
    cellHoverBackground: '#FAF5FF',
    markedBackground: '#FAF5FF',
    markedBorder: '#D8B4FE',
    markedText: 'rgba(88, 28, 135, 0.5)',
    freeBackground: 'linear-gradient(90deg, #A855F7 0%, #EC4899 100%)',
    freeBorder: '#D8B4FE',
    freeText: '#FFFFFF',
    gradientStart: '#FAF5FF',
    gradientMid: '#FCE7F3',
    gradientEnd: '#FEF9C3',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: { card: 12, cell: 8 },
    shadows: {
      card: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    },
  },
  typography: {
    fontFamily: 'sans',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    freeFontSize: 0.75,
    freeFontWeight: 700,
  },
  layout: {
    cardPadding: 2,
    cellGap: 0.5,
    showHeader: false,
  },
  customizable: [
    'colors.gradientStart',
    'colors.gradientMid',
    'colors.gradientEnd',
    'colors.cellBorder',
    'colors.freeBackground',
  ],
  tags: ['gradient', 'soft', 'purple', 'pink', 'yellow'],
};

// Export all basic themes
export const basicThemes: ThemePreset[] = [
  defaultTheme,
  vintageTheme,
  whimsicalTheme,
  modernTheme,
  illustratedTheme,
  sunsetTheme,
  oceanTheme,
  forestTheme,
  midnightTheme,
  pastelTheme,
];
