/**
 * Extravagant Theme Presets
 * Advanced themes with glassmorphism, neon glows, and animated effects
 */

import type { ThemePreset } from '../types';

export const spotifyWrappedTheme: ThemePreset = {
  id: 'spotify-wrapped',
  name: 'Spotify Wrapped',
  category: 'extravagant',
  description: 'Vibrant Spotify green and hot pink with glassmorphism - authentic Wrapped 2023 style',
  colors: {
    cardBackground: 'linear-gradient(135deg, #1DB954 0%, #1ed760 50%, #1DB954 100%)',
    cardBorder: 'rgba(255, 20, 147, 0.3)',
    cellBackground: 'rgba(255, 20, 147, 0.12)',
    cellBorder: 'rgba(255, 20, 147, 0.3)',
    cellText: '#000000',
    cellHoverBackground: 'rgba(255, 20, 147, 0.25)',
    cellHoverBorder: 'rgba(255, 20, 147, 0.5)',
    markedBackground: 'rgba(255, 20, 147, 0.18)',
    markedBorder: 'rgba(255, 20, 147, 0.4)',
    markedText: 'rgba(0, 0, 0, 0.5)',
    freeBackground: 'linear-gradient(135deg, #FF1493 0%, #FF69B4 100%)',
    freeBorder: 'rgba(255, 20, 147, 0.5)',
    freeText: '#000000',
    headerBackground: 'transparent',
    headerText: '#FFFFFF',
    glowColor: '#FF1493',
    accentColor: '#FF69B4',
    gradientStart: '#1DB954',
    gradientMid: '#1ed760',
    gradientEnd: '#1DB954',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 1,
    glassmorphism: {
      enabled: true,
      blur: 16,
      opacity: 0.12,
      borderOpacity: 0.25,
    },
    neonGlow: {
      enabled: false,
      color: '#FF1493',
      intensity: 3,
      animated: false,
    },
    shadows: {
      card: '0 20px 40px rgba(255, 20, 147, 0.3), 0 8px 16px rgba(29, 185, 84, 0.2)',
      cell: 'none',
      cellHover: '0 8px 20px rgba(255, 20, 147, 0.4)',
    },
    gradientAnimation: {
      enabled: true,
      duration: 8,
      direction: 'diagonal',
    },
    overlayPattern: {
      type: 'dots',
      opacity: 0.15,
      color: '#FF69B4',
    },
    borderRadius: { card: 24, cell: 12 },
    decorativeElements: {
      enabled: true,
      elements: [
        // Chrome tube top-left
        {
          type: 'chrome-tube',
          position: { top: '-50px', left: '-30px' },
          size: 250,
          rotation: -25,
          opacity: 0.9,
          colors: ['#2a2a2a', '#d0d0d0', '#ffffff'],
        },
        // Chrome tube top-right
        {
          type: 'chrome-tube',
          position: { top: '-30px', right: '-40px' },
          size: 220,
          rotation: 35,
          opacity: 0.9,
          colors: ['#2a2a2a', '#c0c0c0', '#f5f5f5'],
        },
        // Chrome tube bottom-left
        {
          type: 'chrome-tube',
          position: { bottom: '-40px', left: '-20px' },
          size: 200,
          rotation: 55,
          opacity: 0.85,
          colors: ['#1a1a1a', '#b8b8b8', '#e8e8e8'],
        },
        // Holographic bubble top-left corner
        {
          type: 'holographic-bubble',
          position: { top: '-20px', left: '-20px' },
          size: 180,
          opacity: 0.8,
          colors: ['#FF00FF', '#FF1493', '#00FFFF', '#1DB954', '#FF69B4'],
        },
        // Holographic bubble top-right corner
        {
          type: 'holographic-bubble',
          position: { top: '-30px', right: '-30px' },
          size: 200,
          opacity: 0.75,
          colors: ['#FF1493', '#00FFFF', '#FF69B4', '#1ed760', '#FF00FF'],
        },
        // Holographic bubble bottom-right
        {
          type: 'holographic-bubble',
          position: { bottom: '-40px', right: '-35px' },
          size: 220,
          opacity: 0.7,
          colors: ['#00FFFF', '#FF69B4', '#1DB954', '#FF1493', '#FF00FF'],
        },
        // Small glow orb accent top
        {
          type: 'glow-orb',
          position: { top: '10%', right: '5%' },
          size: 100,
          opacity: 0.4,
          colors: ['#FF1493', '#FF69B4'],
        },
        // Small glow orb accent bottom
        {
          type: 'glow-orb',
          position: { bottom: '8%', left: '8%' },
          size: 120,
          opacity: 0.3,
          colors: ['#1DB954', '#1ed760'],
        },
      ],
    },
  },
  typography: {
    fontFamily: 'montserrat',
    cellFontSize: 0.625,
    cellFontWeight: 700,
    cellTextTransform: 'uppercase',
    cellLetterSpacing: 0.02,
    headerFontSize: 3,
    headerFontWeight: 900,
    headerLetterSpacing: -0.02,
    freeFontSize: 0.875,
    freeFontWeight: 900,
    freeTextTransform: 'uppercase',
  },
  layout: {
    cardPadding: 3,
    cellGap: 0.75,
    showHeader: false,
  },
  customizable: [
    'colors.gradientStart',
    'colors.gradientMid',
    'colors.gradientEnd',
    'colors.glowColor',
    'effects.glassmorphism.blur',
    'effects.glassmorphism.opacity',
    'effects.gradientAnimation.duration',
    'typography.cellFontWeight',
  ],
  tags: ['glassmorphism', 'gradient', 'green', 'pink', 'vibrant', 'animated', 'spotify'],
};

export const tronLegacyTheme: ThemePreset = {
  id: 'tron-legacy',
  name: 'Tron Legacy',
  category: 'extravagant',
  description: 'Futuristic neon blue glows on dark background with circuit patterns',
  colors: {
    cardBackground: '#000000',
    cardBorder: '#00d9ff',
    cellBackground: 'rgba(0, 217, 255, 0.03)',
    cellBorder: '#00d9ff',
    cellText: '#00d9ff',
    cellHoverBackground: 'rgba(0, 217, 255, 0.1)',
    cellHoverBorder: '#00d9ff',
    markedBackground: 'rgba(0, 217, 255, 0.08)',
    markedBorder: '#00d9ff',
    markedText: 'rgba(0, 217, 255, 0.5)',
    freeBackground: 'rgba(0, 217, 255, 0.15)',
    freeBorder: '#00d9ff',
    freeText: '#FFFFFF',
    headerBackground: 'transparent',
    headerText: '#00d9ff',
    glowColor: '#00d9ff',
    accentColor: '#ff00ff',
  },
  effects: {
    borderStyle: 'neon-glow',
    borderWidth: 2,
    neonGlow: {
      enabled: true,
      color: '#00d9ff',
      intensity: 6,
      animated: true,
      pulseSpeed: 2,
    },
    shadows: {
      card: '0 0 30px rgba(0, 217, 255, 0.5), 0 0 60px rgba(0, 217, 255, 0.3), inset 0 0 20px rgba(0, 217, 255, 0.1)',
      cell: '0 0 10px rgba(0, 217, 255, 0.3)',
      cellHover: '0 0 20px rgba(0, 217, 255, 0.6), 0 0 40px rgba(0, 217, 255, 0.4)',
    },
    overlayPattern: {
      type: 'circuit',
      opacity: 0.05,
      color: '#00d9ff',
    },
    borderRadius: { card: 4, cell: 2 },
  },
  typography: {
    fontFamily: 'geist-mono',
    cellFontSize: 0.5625,
    cellFontWeight: 400,
    cellTextTransform: 'uppercase',
    cellLetterSpacing: 0.1,
    headerFontSize: 2.5,
    headerFontWeight: 700,
    headerLetterSpacing: 0.15,
    freeFontSize: 0.75,
    freeFontWeight: 700,
    freeTextTransform: 'uppercase',
  },
  layout: {
    cardPadding: 2.5,
    cellGap: 0.75,
    showHeader: false,
  },
  customizable: [
    'colors.glowColor',
    'colors.cellBorder',
    'effects.neonGlow.intensity',
    'effects.neonGlow.animated',
    'effects.neonGlow.pulseSpeed',
    'effects.overlayPattern.opacity',
    'typography.cellLetterSpacing',
  ],
  tags: ['neon', 'futuristic', 'cyan', 'dark', 'glow', 'sci-fi'],
};

export const cyberpunkTheme: ThemePreset = {
  id: 'cyberpunk',
  name: 'Cyberpunk',
  category: 'extravagant',
  description: 'High-tech neon aesthetic with pink and cyan glows',
  colors: {
    cardBackground: 'linear-gradient(135deg, #0a0012 0%, #1a0028 100%)',
    cardBorder: '#ff00ff',
    cellBackground: 'rgba(255, 0, 255, 0.05)',
    cellBorder: '#ff00ff',
    cellText: '#00ffff',
    cellHoverBackground: 'rgba(255, 0, 255, 0.12)',
    cellHoverBorder: '#ff00ff',
    markedBackground: 'rgba(255, 0, 255, 0.1)',
    markedBorder: '#ff00ff',
    markedText: 'rgba(0, 255, 255, 0.5)',
    freeBackground: 'linear-gradient(135deg, #ff00ff 0%, #00ffff 100%)',
    freeBorder: '#ff00ff',
    freeText: '#000000',
    headerBackground: 'transparent',
    headerText: '#ff00ff',
    glowColor: '#ff00ff',
    accentColor: '#00ffff',
    gradientStart: '#0a0012',
    gradientEnd: '#1a0028',
  },
  effects: {
    borderStyle: 'neon-glow',
    borderWidth: 2,
    neonGlow: {
      enabled: true,
      color: '#ff00ff',
      intensity: 7,
      animated: true,
      pulseSpeed: 1.5,
    },
    shadows: {
      card: '0 0 40px rgba(255, 0, 255, 0.4), 0 0 80px rgba(255, 0, 255, 0.2)',
      cell: '0 0 8px rgba(255, 0, 255, 0.3)',
      cellHover: '0 0 15px rgba(255, 0, 255, 0.5), 0 0 30px rgba(0, 255, 255, 0.3)',
    },
    overlayPattern: {
      type: 'grid',
      opacity: 0.08,
      color: '#ff00ff',
    },
    borderRadius: { card: 8, cell: 4 },
  },
  typography: {
    fontFamily: 'geist-mono',
    cellFontSize: 0.625,
    cellFontWeight: 600,
    cellTextTransform: 'uppercase',
    cellLetterSpacing: 0.05,
    headerFontSize: 3,
    headerFontWeight: 900,
    headerLetterSpacing: 0.1,
    freeFontSize: 0.875,
    freeFontWeight: 900,
    freeTextTransform: 'uppercase',
  },
  layout: {
    cardPadding: 2.5,
    cellGap: 0.75,
    showHeader: false,
  },
  customizable: [
    'colors.glowColor',
    'colors.accentColor',
    'colors.cellText',
    'effects.neonGlow.intensity',
    'effects.neonGlow.pulseSpeed',
    'effects.overlayPattern.opacity',
  ],
  tags: ['neon', 'cyberpunk', 'pink', 'cyan', 'futuristic', 'dark'],
};

export const artDecoTheme: ThemePreset = {
  id: 'art-deco',
  name: 'Art Deco',
  category: 'extravagant',
  description: 'Elegant 1920s inspired design with gold accents and geometric patterns',
  colors: {
    cardBackground: 'linear-gradient(135deg, #0a0a0a 0%, #1a1410 100%)',
    cardBorder: '#d4af37',
    cellBackground: 'rgba(212, 175, 55, 0.05)',
    cellBorder: '#d4af37',
    cellText: '#f5e6d3',
    cellHoverBackground: 'rgba(212, 175, 55, 0.12)',
    cellHoverBorder: '#d4af37',
    markedBackground: 'rgba(212, 175, 55, 0.1)',
    markedBorder: '#d4af37',
    markedText: 'rgba(245, 230, 211, 0.5)',
    freeBackground: 'linear-gradient(135deg, #d4af37 0%, #aa8a2e 100%)',
    freeBorder: '#d4af37',
    freeText: '#0a0a0a',
    headerBackground: 'transparent',
    headerText: '#d4af37',
    glowColor: '#d4af37',
    gradientStart: '#0a0a0a',
    gradientEnd: '#1a1410',
  },
  effects: {
    borderStyle: 'geometric',
    borderWidth: 2,
    neonGlow: {
      enabled: true,
      color: '#d4af37',
      intensity: 3,
      animated: false,
    },
    shadows: {
      card: '0 10px 30px rgba(212, 175, 55, 0.2), 0 4px 12px rgba(212, 175, 55, 0.15)',
      cell: '0 2px 8px rgba(212, 175, 55, 0.1)',
      cellHover: '0 4px 16px rgba(212, 175, 55, 0.25)',
    },
    overlayPattern: {
      type: 'geometric',
      opacity: 0.1,
      color: '#d4af37',
    },
    borderRadius: { card: 0, cell: 0 },
  },
  typography: {
    fontFamily: 'serif',
    cellFontSize: 0.625,
    cellFontWeight: 500,
    cellTextTransform: 'uppercase',
    cellLetterSpacing: 0.08,
    headerFontSize: 3,
    headerFontWeight: 700,
    headerLetterSpacing: 0.15,
    freeFontSize: 0.875,
    freeFontWeight: 700,
    freeTextTransform: 'uppercase',
  },
  layout: {
    cardPadding: 3,
    cellGap: 0.5,
    showHeader: false,
    showCornerDecorations: true,
  },
  customizable: [
    'colors.glowColor',
    'colors.cellText',
    'effects.neonGlow.intensity',
    'effects.overlayPattern.opacity',
    'typography.cellLetterSpacing',
  ],
  tags: ['elegant', 'gold', 'geometric', '1920s', 'luxury'],
};

export const vaporwaveTheme: ThemePreset = {
  id: 'vaporwave',
  name: 'Vaporwave',
  category: 'extravagant',
  description: 'Retro-futuristic aesthetic with pink, purple, and cyan gradients',
  colors: {
    cardBackground: 'linear-gradient(135deg, #ff71ce 0%, #01cdfe 50%, #b967ff 100%)',
    cardBorder: 'rgba(255, 255, 255, 0.3)',
    cellBackground: 'rgba(255, 255, 255, 0.15)',
    cellBorder: 'rgba(255, 255, 255, 0.4)',
    cellText: '#ffffff',
    cellHoverBackground: 'rgba(255, 255, 255, 0.25)',
    cellHoverBorder: 'rgba(255, 255, 255, 0.6)',
    markedBackground: 'rgba(255, 255, 255, 0.2)',
    markedBorder: 'rgba(255, 255, 255, 0.5)',
    markedText: 'rgba(255, 255, 255, 0.6)',
    freeBackground: 'rgba(255, 255, 255, 0.9)',
    freeBorder: 'rgba(255, 255, 255, 0.6)',
    freeText: '#ff71ce',
    headerBackground: 'transparent',
    headerText: '#ffffff',
    glowColor: '#ff71ce',
    accentColor: '#01cdfe',
    gradientStart: '#ff71ce',
    gradientMid: '#01cdfe',
    gradientEnd: '#b967ff',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 3,
    glassmorphism: {
      enabled: true,
      blur: 10,
      opacity: 0.15,
      borderOpacity: 0.4,
    },
    neonGlow: {
      enabled: true,
      color: '#ff71ce',
      intensity: 4,
      animated: true,
      pulseSpeed: 3,
    },
    shadows: {
      card: '0 8px 32px rgba(255, 113, 206, 0.3), 0 4px 16px rgba(1, 205, 254, 0.2)',
      cell: 'none',
      cellHover: '0 4px 16px rgba(255, 255, 255, 0.3)',
    },
    gradientAnimation: {
      enabled: true,
      duration: 10,
      direction: 'diagonal',
    },
    overlayPattern: {
      type: 'grid',
      opacity: 0.15,
      color: '#ffffff',
    },
    borderRadius: { card: 16, cell: 8 },
  },
  typography: {
    fontFamily: 'montserrat',
    cellFontSize: 0.625,
    cellFontWeight: 700,
    cellTextTransform: 'uppercase',
    cellLetterSpacing: 0.05,
    headerFontSize: 3.5,
    headerFontWeight: 900,
    headerLetterSpacing: 0.1,
    freeFontSize: 0.875,
    freeFontWeight: 900,
    freeTextTransform: 'uppercase',
  },
  layout: {
    cardPadding: 3,
    cellGap: 0.75,
    showHeader: false,
  },
  customizable: [
    'colors.gradientStart',
    'colors.gradientMid',
    'colors.gradientEnd',
    'effects.glassmorphism.blur',
    'effects.glassmorphism.opacity',
    'effects.neonGlow.intensity',
    'effects.neonGlow.pulseSpeed',
    'effects.gradientAnimation.duration',
  ],
  tags: ['retro', 'vaporwave', 'gradient', 'pink', 'cyan', 'animated'],
};

export const holographicTheme: ThemePreset = {
  id: 'holographic',
  name: 'Holographic',
  category: 'extravagant',
  description: 'Iridescent rainbow gradients with glassmorphism',
  colors: {
    cardBackground: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #4facfe 75%, #00f2fe 100%)',
    cardBorder: 'rgba(255, 255, 255, 0.3)',
    cellBackground: 'rgba(255, 255, 255, 0.12)',
    cellBorder: 'rgba(255, 255, 255, 0.3)',
    cellText: '#ffffff',
    cellHoverBackground: 'rgba(255, 255, 255, 0.2)',
    cellHoverBorder: 'rgba(255, 255, 255, 0.5)',
    markedBackground: 'rgba(255, 255, 255, 0.18)',
    markedBorder: 'rgba(255, 255, 255, 0.4)',
    markedText: 'rgba(255, 255, 255, 0.6)',
    freeBackground: 'rgba(255, 255, 255, 0.95)',
    freeBorder: 'rgba(255, 255, 255, 0.5)',
    freeText: '#667eea',
    headerBackground: 'transparent',
    headerText: '#ffffff',
    glowColor: '#667eea',
    gradientStart: '#667eea',
    gradientEnd: '#00f2fe',
  },
  effects: {
    borderStyle: 'solid',
    borderWidth: 2,
    glassmorphism: {
      enabled: true,
      blur: 16,
      opacity: 0.12,
      borderOpacity: 0.3,
    },
    shadows: {
      card: '0 8px 32px rgba(102, 126, 234, 0.3), 0 4px 16px rgba(244, 143, 177, 0.2)',
      cell: 'none',
      cellHover: '0 8px 24px rgba(255, 255, 255, 0.25)',
    },
    gradientAnimation: {
      enabled: true,
      duration: 6,
      direction: 'diagonal',
    },
    borderRadius: { card: 20, cell: 10 },
  },
  typography: {
    fontFamily: 'montserrat',
    cellFontSize: 0.625,
    cellFontWeight: 600,
    cellTextTransform: 'none',
    cellLetterSpacing: 0.01,
    headerFontSize: 3,
    headerFontWeight: 800,
    freeFontSize: 0.875,
    freeFontWeight: 900,
  },
  layout: {
    cardPadding: 3,
    cellGap: 0.75,
    showHeader: false,
  },
  customizable: [
    'effects.glassmorphism.blur',
    'effects.glassmorphism.opacity',
    'effects.gradientAnimation.duration',
    'typography.cellFontWeight',
  ],
  tags: ['holographic', 'rainbow', 'iridescent', 'glassmorphism', 'animated'],
};

// Export all extravagant themes
export const extravagantThemes: ThemePreset[] = [
  spotifyWrappedTheme,
  tronLegacyTheme,
  cyberpunkTheme,
  artDecoTheme,
  vaporwaveTheme,
  holographicTheme,
];
